Repository all-night-coding/My-Wine-Cellar, pull requests merged in 2022-06, with the labels that each got.

#6 Feat: Frontend 초기설정
  mwc-frontend/assets/buefy.png
  mwc-frontend/assets/styles/scss/buefy.scss
  mwc-frontend/components/NuxtLogo.vue
  mwc-frontend/components/QuillEditor.vue
  mwc-frontend/nuxt.config.js
  mwc-frontend/package-lock.json
  mwc-frontend/package.json
  mwc-frontend/plugins/infiniteloading.js
  mwc-frontend/plugins/vue-quill-editor.js
Labels: Feat

#8 Feat: Backend 초기설정
  .idea/.gitignore
  .idea/misc.xml
  .idea/modules.xml
  .idea/vcs.xml
  My-Wine-Celler.iml
  mwc-backend/.gitignore
  mwc-backend/.mvn/wrapper/maven-wrapper.jar
  mwc-backend/.mvn/wrapper/maven-wrapper.properties
  mwc-backend/mvnw
  mwc-backend/mvnw.cmd
  mwc-backend/pom.xml
  mwc-backend/src/main/java/com/example/mwcbackend/MwcBackendApplication.java
  mwc-backend/src/main/resources/application.properties
  mwc-backend/src/test/java/com/example/mwcbackend/MwcBackendApplicationTests.java
Labels: Docs

#9 Docs: README.md 수정
  README.md
Labels: Docs

#11 Feat: Main Page 기본 레이아웃 구현
  mwc-frontend/assets/styles/scss/main.scss
  mwc-frontend/components/Card.vue
  mwc-frontend/components/Navbar.vue
  mwc-frontend/components/Title.vue
  mwc-frontend/components/Tutorial.vue
  mwc-frontend/layouts/default.vue
  mwc-frontend/nuxt.config.js
  mwc-frontend/pages/index.vue
  mwc-frontend/pages/inspire.vue
Labels: Feat

#14 Feat: Social Login 기본 Setting
  mwc-frontend/nuxt.config.js
Labels: Feat

#17 Feat: 랜덤피드 페이지 기본 레이아웃 구현
  mwc-frontend/assets/styles/scss/main.scss
  mwc-frontend/components/Navbar.vue
  mwc-frontend/components/Title.vue
  mwc-frontend/layouts/default.vue
  mwc-frontend/pages/index.vue
  mwc-frontend/pages/wine-board.vue
Labels: Feat

#16 Feature/12/swagger api
  mwc-backend/.gitignore
  mwc-backend/.mvn/wrapper/maven-wrapper.jar
  mwc-backend/.mvn/wrapper/maven-wrapper.properties
  mwc-backend/build.gradle
  mwc-backend/gradle/wrapper/gradle-wrapper.jar
  mwc-backend/gradle/wrapper/gradle-wrapper.properties
  mwc-backend/gradlew
  mwc-backend/gradlew.bat
  mwc-backend/mvnw
  mwc-backend/mvnw.cmd
  mwc-backend/pom.xml
  mwc-backend/settings.gradle
  mwc-backend/src/main/java/com/example/mwcbackend/MwcBackendApplication.java
  mwc-backend/src/main/java/com/example/mwcbackend/config/SwaggerConfig.java
  mwc-backend/src/main/java/com/example/mwcbackend/controller/TestController.java
  mwc-backend/src/main/resources/application.properties
  mwc-backend/src/test/java/com/example/mwcbackend/MwcBackendApplicationTests.java
Labels: Feat

#20 Feat: 글쓰기 페이지 기본 구현
  mwc-frontend/components/Navbar.vue
  mwc-frontend/nuxt.config.js
  mwc-frontend/pages/add-wine.vue
  mwc-frontend/pages/index.vue
  mwc-frontend/pages/wine-board.vue
Labels: Feat

#27 Feature/26/rebuild for java18
  mwc-backend/.DS_Store
  mwc-backend/.gitignore
Labels: Docs, Chore

#29 Feat: my-page 기본 레이아웃 구현
  mwc-frontend/assets/styles/scss/main.scss
  mwc-frontend/components/Title.vue
  mwc-frontend/layouts/default.vue
  mwc-frontend/pages/index.vue
  mwc-frontend/pages/my-page.vue
  mwc-frontend/static/img/profile-image.png
Labels: Feat

#31 Refactor: 메인 페이지 디자인 수정
  mwc-frontend/assets/styles/scss/buefy.scss
  mwc-frontend/assets/styles/scss/colors.scss
  mwc-frontend/assets/styles/scss/custom.scss
  mwc-frontend/components/Navbar.vue
  mwc-frontend/components/Title.vue
  mwc-frontend/layouts/default.vue
  mwc-frontend/nuxt.config.js
  mwc-frontend/pages/index.vue
  mwc-frontend/static/img/wall.jpg
  mwc-frontend/static/img/wine.jpeg
Labels: Refactor

#33 Refactor: 랜덤 피드 페이지 디자인 수정
  mwc-frontend/pages/wine-board.vue
  mwc-frontend/vercel.json
Labels: Refactor

#28 add Code Convention File in Templates
  mwc-backend/src/main/resources/templates/naver-intellij-formatter.xml
Labels: Docs

#39 gitignore update -dv, mac cache
  mwc-backend/.gitignore
Labels: Docs

#40 Refactor: my page 디자인 수정
  README.md
  mwc-frontend/assets/styles/scss/colors.scss
  mwc-frontend/pages/add-wine.vue
  mwc-frontend/pages/my-page.vue
  mwc-frontend/static/img/badge.png
Labels: Refactor, Docs

#46 Fix: My Page 버그 수정
  mwc-frontend/components/QuillEditor.vue
  mwc-frontend/package-lock.json
  mwc-frontend/package.json
  mwc-frontend/pages/add-wine.vue
  mwc-frontend/pages/my-page.vue
Labels: Fix, Refactor

#49 Feat: 친구 페이지 기본 구현
  mwc-frontend/assets/styles/scss/colors.scss
  mwc-frontend/pages/friends-list.vue
  mwc-frontend/pages/my-page.vue
Labels: Feat

#51 Refactor: BEM Method 적용
  mwc-frontend/components/Navbar.vue
  mwc-frontend/components/Title.vue
  mwc-frontend/layouts/default.vue
  mwc-frontend/layouts/error.vue
  mwc-frontend/nuxt.config.js
  mwc-frontend/package-lock.json
  mwc-frontend/package.json
  mwc-frontend/pages/friends-list.vue
  mwc-frontend/pages/index.vue
  mwc-frontend/pages/my-page.vue
  mwc-frontend/plugins/lottie-vue-player.client.js
  mwc-frontend/static/lottie/error.json
Labels: Refactor
